version: '3.4'

networks:
  main-net:

services:

  loss-prevention:
    image: rsp/loss-prevention-service:dev
    networks:
      - main-net
    extra_hosts:
      - "edgex-core-data:172.17.0.1"
      - "edgex-support-logging:172.17.0.1"
      - "edgex-core-consul:172.17.0.1"
      - "edgex-core-command:172.17.0.1"
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
    security_opt:
      - apparmor=unconfined
    environment:
      DISPLAY: unix:0
      loggingLevel: "debug"
      telemetryEndpoint: ""
      telemetryDataStoreName: ""
#      ipCameraStreamUrl: ""
      usbCameraDeviceIndex: 0
      serviceName: "Loss Prevention Example App"
      videoUrlBase: "http://localhost:9091/material-dashboard/view.html?v="
#      OPENCV_LOG_LEVEL: "DEBUG"
#      OPENCV_VIDEOIO_DEBUG: "1"
      port: "8080"
    volumes:
      - ./recordings:/recordings
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
    devices:
      - /dev/video0:/dev/video0

  nginx:
    image: nginx:latest
    networks:
      - main-net
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
    ports:
      - "9091:80"
    volumes:
      - ./video-server/www:/usr/share/nginx/html
      - ./recordings:/usr/share/nginx/html/recordings
