version: '3.4'

networks:
  main-net:

volumes:
  www-root:

services:

  loss-prevention:
    image: rsp/loss-prevention-service:dev
    networks:
      - main-net
    extra_hosts:
      - "edgex-core-data:172.17.0.1"
      - "edgex-support-logging:172.17.0.1"
      - "edgex-core-consul:172.17.0.1"
      - "edgex-core-command:172.17.0.1"
      - "edgex-support-notifications:172.17.0.1"
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
    security_opt:
      - apparmor=unconfined
    ports:
      - "9092:8080"
    environment:
      serviceName: "Loss Prevention Example App"
      loggingLevel: "debug"
      port: "8080"
      enableCORS: "true"
      corsOrigin: "*"

      # NOTE: Point this to the nginx container port
      videoUrlBase: "http://localhost:9091/recordings"

      liveView: "true"
      fullscreenView: "false"
      showVideoDebugStats: "true"
      # Note: If not using live view remove this
      DISPLAY: "unix:0"

      videoCaptureFOURCC: "MJPG"
      recordingDuration: 15
      videoResolutionWidth: 1280
      videoResolutionHeight: 720
      imageProcessScale: 2
      videoOutputFps: 25
      videoOutputCodec: "avc1"
      videoOutputExtension: ".mp4"

      saveObjectDetectionsToDisk: "true"
      # Below are the various OpenCV detection algorithms you can enable
      #     enableXXXDetection: enable the real time detection of specified feature
      #    xxxDetectionXmlFile: (advanced option) specify the cascade xml file to be used. Available options can be found in `res/data/haarcascades`
      # xxxDetectionAnnotation: the text written above the detected object. Set to "" to not display any text
      #      xxxDetectionColor: Specify the color used to draw boxes around the detected object. Format is a hex value (do not use quotations) in the format of 0xRRGGBB where RR GG and BB are 2 hex digit values of red, green and blue respectively.

      # Face Detection
      enableFaceDetection: "true"
      faceDetectionXmlFile: "haarcascade_frontalface_default.xml"
      faceDetectionAnnotation: "Bacon Thief!"
      faceDetectionColor: 0xff0000

      # Profile Face Detection
      enableProfileFaceDetection: "true"
      profileFaceDetectionXmlFile: "haarcascade_profileface.xml"
      profileFaceDetectionAnnotation: "Employee"
      profileFaceDetectionColor: 0x0000ff

      # Upper Body Detection
      enableUpperBodyDetection: "true"
      upperBodyDetectionXmlFile: "haarcascade_upperbody.xml"
      upperBodyDetectionAnnotation: "Employee"
      upperBodyDetectionColor: 0xffffff

      # Full Body Detection
      enableFullBodyDetection: "true"
      fullBodyDetectionXmlFile: "haarcascade_fullbody.xml"
      fullBodyDetectionAnnotation: "Bacon Thief!"
      fullBodyDetectionColor: 0xffff00

      # Eye Detection (Warning: should probably be turned off as it is slow and doesnt provide much usefulness)
      enableEyeDetection: "false"
      eyeDetectionXmlFile: "haarcascade_eye.xml"
      eyeDetectionAnnotation: ""
      eyeDetectionColor: 0x0000ff

      # NOTE: If using a usb camera, make sure this number matches the one in the `devices` field below
      usbCameraDeviceIndex: 0
#      ipCameraStreamUrl: "rtsp://admin:@192.168.3.108:554"

      epcFilter: "*"
#      epcFilter: "3035*72[CB][0-6EF]"
      skuFilter: "*"

      emailSubscribers: ""

    devices:
      # NOTE: If using a usb camera, make sure to map the right one here
      - /dev/video0:/dev/video0

    volumes:
      - ./recordings:/recordings
      # NOTE: If not using liveView, these two volumes can be removed
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus

  nginx:
    image: nginx:latest
    networks:
      - main-net
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
    ports:
      - "9091:80"
    volumes:
      - www-root:/usr/share/nginx/html
      - ./recordings:/usr/share/nginx/html/recordings
