[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'loss-prevention-service'
Timeout = '5s'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'
  
[MessageBus]
Type = 'zero'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = ""

[Binding]
Type="messagebus"
SubscribeTopic=""
