[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'loss-prevention-service'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Loss Prevention Service'
Timeout = '5s'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

  [Clients.Notifications]
  Protocol = 'http'
  Host = 'edgex-support-notifications'
  Port = 48060

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'
  
[MessageBus]
Type = 'zero'
    [MessageBus.SubscribeHost]
        Host = 'edgex-core-data'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false

[Binding]
Type="messagebus"
SubscribeTopic=""
